# Generated by Django 4.2.2 on 2025-10-14 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('reading', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', '未学習'), ('learning', '学習中'), ('mastered', '習得済み')], default='new', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='flashcards.folder')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('folder', 'term'), name='uniq_term_per_folder'),
        ),
    ]
